version: "3.8"

services:

  db:
    build: mariadb
    container_name: gsb_frais_db
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./:/var/www/GSB-Frais
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  www:
    build: php
    container_name: gsb_frais_www
    ports:
      - "9973:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/GSB-Frais
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
