#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
   path: /
   controller: App\Controller\AccueilController::index

connexion:
   path: /connexion
   controller: App\Controller\ConnexionController::connexion

deconnexion:
   path: /deconnexion
   controller: App\Controller\ConnexionController::deconnexion
   methods: GET

visiteur:
   path: /visiteur
   controller: App\Controller\VisiteurController::index

saisir_fiche_frais:
   path: /visiteur/saisir_fiche_frais
   controller: App\Controller\VisiteurController::saisirFicheFrais

supprimer_frais_hors_forfait:
   path: /visiteur/saisir_fiche_frais/supprimer_frais_hors_forfait/{id}
   controller: App\Controller\VisiteurController::supprimerFraisHorsForfait

consulter_fiches_frais:
   path: /visiteur/consulter_fiches_frais
   controller: App\Controller\VisiteurController::consulterFichesFrais

consulter_detail_fiche_frais:
   path: /visiteur/consulter_detail_fiche_frais/{idFicheFrais}
   controller: App\Controller\VisiteurController::consulterDetailFicheFrais

comptable:
   path: /comptable
   controller: App\Controller\ComptableController::index
   
selectionner_fiche_frais:
   path: /comptable/selectionner_fiche_frais
   controller: App\Controller\ComptableController::selectionnerFicheFrais

administrer_fiche_frais:
   path: /comptable/administrer_fiche_frais/{idFicheFrais}
   controller: App\Controller\ComptableController::administrerFicheFrais

modifier_statut_frais_hors_forfait:
   path: /comptable/modifier_statut_frais_hors_forfait/{id}
   controller: App\Controller\ComptableController::modifierStatutFraisHorsForfait

valider_fiche_frais:
   path: /comptable/valider_fiche_frais/{id}
   controller: App\Controller\ComptableController::validerFicheFrais
   
rembourser_fiche_frais:
   path: /comptable/rembourser_fiche_frais/{id}
   controller: App\Controller\ComptableController::rembouserFicheFrais
