#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
   path: /
   controller: App\Controller\AccueilController::index

accueil:
   path: /accueil
   controller: App\Controller\AccueilController::accueil

# accueil:
#    path: /
#    controller: App\Controller\ConnexionController::index

se_connecter:
   path: /se_connecter/{echec}
   controller: App\Controller\ConnexionController::seConnecter
   defaults:
      echec: false

se_deconnecter:
   path: /se_deconnecter
   controller: App\Controller\ConnexionController::seDeconnecter

visiteur:
   path: /visiteur
   controller: App\Controller\VisiteurController::index

saisir_fiche_frais:
   path: /visiteur/saisir_fiche_frais
   controller: App\Controller\VisiteurController::saisirFicheFrais

supprimer_fraishorsforfait:
   path: /visiteur/saisir_fiche_frais/supprimer_fraishorsforfait/{id}
   controller: App\Controller\VisiteurController::supprimerFraisHorsForfait

consulter_fiches_frais:
   path: /visiteur/consulter_fiches_frais
   controller: App\Controller\VisiteurController::consulterFichesFrais

consulter_detail_fiche_frais:
   path: /visiteur/consulter_detail_fiche_frais/{id}
   controller: App\Controller\VisiteurController::consulterDetailFicheFrais

comptable:
   path: /comptable
   controller: App\Controller\ComptableController::index

valider_fiche_frais:
   path: /comptable/valider_fiche_frais
   controller: App\Controller\ComptableController::validerFicheFrais
   
suivre_fiche_frais:
   path: /comptable/suivre_fiche_frais
   controller: App\Controller\ComptableController::SuivreFicheFrais

